language: java
jdk:
- oraclejdk8
- oraclejdk7

deploy:
  provider: script
  script: ./gradlew clean publishPlugins -Pversion=$TRAVIS_TAG -Pgradle.publish.key=$GRADLE_PUBLISH_KEY -Pgradle.publish.secret=$GRADLE_PUBLISH_SECRET
  on:
    jdk: oraclejdk7
    tags: true
